# Generated by Django 6.0 on 2026-01-05 18:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=10)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię Kierowcy')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko Kierowcy')),
                ('company', models.CharField(max_length=200, verbose_name='Nazwa Firmy')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Data Od')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Data Do')),
                ('vehicle_type', models.CharField(choices=[('OSOBOWE', 'Osobowe'), ('CIEZAROWE', 'Ciężarowe'), ('AUTOBUSY', 'Autobusy'), ('MOTOCYKLE', 'Motocykle'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('KOMBI', 'Kombi'), ('COUPE', 'Coupé')], max_length=30, verbose_name='Typ Pojazdu')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje')),
                ('scan_agreement', models.FileField(blank=True, null=True, upload_to='umowy/', verbose_name='Skan Umowy (PDF)')),
                ('status', models.CharField(choices=[('OCZEKUJACE', 'Oczekujące'), ('PRZYJETE', 'Przyjęte'), ('ZATWIERDZONE', 'Zatwierdzone'), ('ODRZUCONE', 'Odrzucone')], default='OCZEKUJACE', max_length=20, verbose_name='Status Rezerwacji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rola', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Menedżer Floty'), ('DRIVER', 'Kierowca'), ('EMPLOYEE', 'Pracownik (Dział HR/Finanse)')], default='EMPLOYEE', max_length=50)),
                ('pin_2fa', models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN 2FA')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_prawa_jazdy', models.CharField(max_length=50)),
                ('data_waznosci_prawa_jazdy', models.DateField(blank=True, null=True)),
                ('kategorie_prawa_jazdy', models.CharField(default='B', max_length=100, verbose_name='Kategorie (np. B, C)')),
                ('data_waznosci_badan', models.DateField(blank=True, null=True, verbose_name='Ważność badań lekarskich')),
                ('aktywny', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_core.fleetcompany')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='umowy/', verbose_name='Plik')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fleet_core.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='Numer VIN')),
                ('registration_number', models.CharField(db_index=True, max_length=10)),
                ('marka', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('data_pierwszej_rejestracji', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('SPRAWNY', 'Sprawny'), ('NIESPRAWNY', 'Niesprawny')], default='SPRAWNY', max_length=20)),
                ('typ_pojazdu', models.CharField(choices=[('OSOBOWE', 'Osobowe'), ('CIEZAROWE', 'Ciężarowe'), ('AUTOBUSY', 'Autobusy'), ('MOTOCYKLE', 'Motocykle'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('KOMBI', 'Kombi'), ('COUPE', 'Coupé')], default='OSOBOWE', max_length=30)),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('BENZYNA', 'Benzyna'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Elektryczny'), ('HYBRID', 'Hybryda'), ('PHEV', 'Hybryda Plug-in'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('HYDROGEN', 'Wodorowy')], default='DIESEL', max_length=20, verbose_name='Rodzaj Paliwa')),
                ('przebieg', models.FloatField(default=0.0)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_core.fleetcompany')),
            ],
            options={
                'db_table': 'app_vehicles',
            },
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(verbose_name='Opis Serwisu/Naprawy')),
                ('data_serwisu', models.DateField(verbose_name='Data Serwisu')),
                ('koszt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('typ_zdarzenia', models.CharField(choices=[('INSPEKCJA', 'Inspekcja'), ('NAPRAWA', 'Naprawa/Serwis'), ('PRZEGLAD', 'Przegląd okresowy'), ('BADANIE_TECH', 'Badanie Techniczne'), ('LEGALIZACJA', 'Legalizacja (Tachograf)')], default='NAPRAWA', max_length=50)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='fleet_core.vehicle')),
            ],
            options={
                'verbose_name': 'Zdarzenie Serwisowe',
                'verbose_name_plural': 'Zdarzenia Serwisowe',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_core.vehicle', verbose_name='Przypisany Pojazd'),
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_polisy', models.CharField(max_length=100, verbose_name='Numer Polisy')),
                ('ubezpieczyciel', models.CharField(max_length=100, verbose_name='Towarzystwo Ubezpieczeniowe')),
                ('data_waznosci_oc', models.DateField(verbose_name='Ważność OC')),
                ('data_waznosci_ac', models.DateField(blank=True, null=True, verbose_name='Ważność AC')),
                ('koszt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='fleet_core.vehicle')),
            ],
            options={
                'verbose_name': 'Polisa Ubezpieczeniowa',
                'verbose_name_plural': 'Polisy Ubezpieczeniowe',
            },
        ),
        migrations.CreateModel(
            name='DamageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(verbose_name='Opis Szkody')),
                ('data_zdarzenia', models.DateField(verbose_name='Data Zdarzenia')),
                ('szacowany_koszt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('zgloszony_do_ubezpieczyciela', models.BooleanField(default=False)),
                ('status_naprawy', models.CharField(choices=[('ZGLOSZONA', 'Zgłoszona'), ('WYCENIANA', 'Wyceniana'), ('W_NAPRAWIE', 'W naprawie'), ('ZAMKNIETA', 'Zamknięta')], default='ZGLOSZONA', max_length=50)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_history', to='fleet_core.vehicle')),
            ],
            options={
                'verbose_name': 'Zdarzenie Szkodowe',
                'verbose_name_plural': 'Zdarzenia Szkodowe',
            },
        ),
        migrations.CreateModel(
            name='VehicleHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wydania', models.DateField(verbose_name='Data Wydania')),
                ('data_zwrotu', models.DateField(blank=True, null=True, verbose_name='Data Zwrotu')),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('kierowca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='fleet_core.driver')),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='fleet_core.vehicle')),
            ],
        ),
    ]
