# Generated by Django 6.0 on 2026-01-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Data Od'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Data Do'),
        ),
    ]
