# Generated by Django 5.2.8 on 2025-12-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(verbose_name='Opis Serwisu/Naprawy')),
                ('data_serwisu', models.DateField(verbose_name='Data Serwisu')),
                ('koszt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('typ_zdarzenia', models.CharField(choices=[('INSPEKCJA', 'Inspekcja/Badanie Tech.'), ('NAPRAWA', 'Naprawa/Serwis'), ('PRZEGLAD', 'Przegląd okresowy')], default='NAPRAWA', max_length=50)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='fleet_core.vehicle')),
            ],
            options={
                'verbose_name': 'Zdarzenie Serwisowe',
                'verbose_name_plural': 'Zdarzenia Serwisowe',
            },
        ),
    ]
