# Generated by Django 5.2.8 on 2025-12-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0002_serviceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_2fa',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN 2FA'),
        ),
    ]
