# Generated by Django 6.0 on 2026-01-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0002_remove_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_core.vehicle', verbose_name='Przypisany Pojazd'),
        ),
    ]
