# Generated by Django 6.0 on 2026-01-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0002_vehicledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='scan_policy_ac',
            field=models.FileField(blank=True, null=True, upload_to='docs/ac/', verbose_name='Polisa AC'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scan_policy_oc',
            field=models.FileField(blank=True, null=True, upload_to='docs/oc/', verbose_name='Polisa OC'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scan_purchase_invoice',
            field=models.FileField(blank=True, null=True, upload_to='docs/faktury/', verbose_name='Faktura Zakupu'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scan_registration_card',
            field=models.FileField(blank=True, null=True, upload_to='docs/dowody/', verbose_name='Skan Dowodu Rej.'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scan_service_book',
            field=models.FileField(blank=True, null=True, upload_to='docs/serwis/', verbose_name='Książka Serwisowa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scan_tech_inspection',
            field=models.FileField(blank=True, null=True, upload_to='docs/badania/', verbose_name='Badanie Techniczne'),
        ),
    ]
