# Generated by Django 6.0 on 2026-01-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0003_vehicle_scan_policy_ac_vehicle_scan_policy_oc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_core.driver', verbose_name='Powiązany Kierowca (Konto)'),
        ),
    ]
