# Generated by Django 5.2.8 on 2025-12-07 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0003_customuser_pin_2fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(verbose_name='Opis Szkody')),
                ('data_zdarzenia', models.DateField(verbose_name='Data Zdarzenia')),
                ('szacowany_koszt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('zgloszony_do_ubezpieczyciela', models.BooleanField(default=False)),
                ('status_naprawy', models.CharField(choices=[('ZGLOSZONA', 'Zgłoszona'), ('WYCENIANA', 'Wyceniana'), ('W_NAPRAWIE', 'W naprawie'), ('ZAMKNIETA', 'Zamknięta')], default='ZGLOSZONA', max_length=50)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_history', to='fleet_core.vehicle')),
            ],
            options={
                'verbose_name': 'Zdarzenie Szkodowe',
                'verbose_name_plural': 'Zdarzenia Szkodowe',
            },
        ),
    ]
