# Generated by Django 6.0 on 2026-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0003_reservation_assigned_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje'),
        ),
    ]
