# Generated by Django 6.0 on 2026-01-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0004_reservation_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='scan_agreement',
            field=models.FileField(blank=True, null=True, upload_to='umowy/', verbose_name='Skan Umowy (PDF)'),
        ),
    ]
