# Generated by Django 5.2.8 on 2025-12-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0004_damageevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rola',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Menedżer Floty'), ('DRIVER', 'Kierowca'), ('EMPLOYEE', 'Pracownik (Dział HR/Finanse)')], default='EMPLOYEE', max_length=50),
        ),
    ]
