# Generated by Django 6.0 on 2026-01-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0004_reservation_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclehandover',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_core.reservation', verbose_name='Źródłowa Rezerwacja'),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='scan_agreement',
            field=models.FileField(blank=True, null=True, upload_to='handovers/umowy/', verbose_name='Umowa Najmu'),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='scan_handover_protocol',
            field=models.FileField(blank=True, null=True, upload_to='handovers/protokoly_wydania/', verbose_name='Protokół Wydania'),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='scan_return_protocol',
            field=models.FileField(blank=True, null=True, upload_to='handovers/protokoly_zwrotu/', verbose_name='Protokół Zwrotu'),
        ),
    ]
