# Generated by Django 6.0 on 2026-01-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0005_reservation_scan_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='umowy/', verbose_name='Plik')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fleet_core.reservation')),
            ],
        ),
    ]
