# Generated by Django 6.0 on 2025-12-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0005_alter_customuser_rola'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_polisy', models.CharField(max_length=100, verbose_name='Numer Polisy')),
                ('ubezpieczyciel', models.CharField(max_length=100, verbose_name='Towarzystwo Ubezpieczeniowe')),
                ('data_waznosci_oc', models.DateField(verbose_name='Ważność OC')),
                ('data_waznosci_ac', models.DateField(blank=True, null=True, verbose_name='Ważność AC')),
                ('koszt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='fleet_core.vehicle')),
            ],
            options={
                'verbose_name': 'Polisa Ubezpieczeniowa',
                'verbose_name_plural': 'Polisy Ubezpieczeniowe',
            },
        ),
    ]
