# Generated by Django 6.0 on 2026-01-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0005_vehiclehandover_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclehandover',
            name='calkowity_koszt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='koszt_brakujacego_paliwa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Dopłata za paliwo'),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='paliwo_start',
            field=models.CharField(choices=[('0', 'Rezerwa'), ('25', '1/4 baku'), ('50', '1/2 baku'), ('75', '3/4 baku'), ('100', 'Pełny bak')], default='100', max_length=10),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='paliwo_stop',
            field=models.CharField(blank=True, choices=[('0', 'Rezerwa'), ('25', '1/4 baku'), ('50', '1/2 baku'), ('75', '3/4 baku'), ('100', 'Pełny bak')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='przebieg_start',
            field=models.IntegerField(default=0, verbose_name='Przebieg przy wydaniu'),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='przebieg_stop',
            field=models.IntegerField(blank=True, null=True, verbose_name='Przebieg przy zwrocie'),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='stawka_za_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Stawka za km (PLN)'),
        ),
    ]
