# Generated by Django 6.0 on 2026-01-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0006_vehiclehandover_calkowity_koszt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Moja Flota Sp. z o.o.', max_length=200, verbose_name='Nazwa Twojej Firmy')),
                ('company_address', models.CharField(default='ul. Przykładowa 1, 00-001 Warszawa', max_length=300, verbose_name='Adres Firmy')),
                ('company_nip', models.CharField(default='000-000-00-00', max_length=20, verbose_name='NIP')),
                ('default_rate_km', models.DecimalField(decimal_places=2, default=0.5, max_digits=6, verbose_name='Domyślna stawka za km (PLN)')),
                ('default_fuel_penalty', models.DecimalField(decimal_places=2, default=50.0, max_digits=6, verbose_name='Domyślna opłata za paliwo (PLN)')),
                ('alert_days', models.IntegerField(default=7, verbose_name='Ile dni wcześniej przypominać o terminach?')),
            ],
        ),
    ]
