# Generated by Django 6.0 on 2025-12-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0006_insurancepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('BENZYNA', 'Benzyna'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Elektryczny'), ('HYBRID', 'Hybryda'), ('PHEV', 'Hybryda Plug-in'), ('LPG', 'LPG'), ('CNG', 'CNG'), ('HYDROGEN', 'Wodorowy')], default='DIESEL', max_length=20, verbose_name='Rodzaj Paliwa'),
        ),
    ]
