# Generated by Django 6.0 on 2025-12-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0007_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='data_waznosci_badan',
            field=models.DateField(blank=True, null=True, verbose_name='Ważność badań lekarskich'),
        ),
        migrations.AddField(
            model_name='driver',
            name='kategorie_prawa_jazdy',
            field=models.CharField(default='B', max_length=100, verbose_name='Kategorie (np. B, C)'),
        ),
    ]
