# Generated by Django 6.0 on 2026-01-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0007_globalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rola',
            field=models.CharField(choices=[('ADMIN', 'Administrator Systemu'), ('LOGISTYKA', 'Dział Logistyki (Pojazdy, Kierowcy)'), ('SERWIS', 'Dział Serwisu (Naprawy, Szkody)'), ('KSIĘGOWOŚĆ', 'Dział Księgowości (Tylko do odczytu)'), ('DRIVER', 'Kierowca (Aplikacja Mobilna)'), ('USER', 'Pracownik (Składanie Rezerwacji)')], default='USER', max_length=20),
        ),
    ]
