# Generated by Django 6.0 on 2025-12-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0009_vehicle_assigned_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_core.fleetcompany'),
        ),
    ]
