# Generated by Django 6.0 on 2025-12-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0010_alter_vehicle_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('SPRAWNY', 'Sprawny'), ('NIESPRAWNY', 'Niesprawny')], default='SPRAWNY', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='typ_pojazdu',
            field=models.CharField(choices=[('OSOBOWE', 'Osobowe'), ('CIEZAROWE', 'Ciężarowe'), ('AUTOBUSY', 'Autobusy'), ('MOTOCYKLE', 'Motocykle'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('KOMBI', 'Kombi'), ('COUPE', 'Coupé')], default='OSOBOWE', max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='uwagi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
