# Generated by Django 6.0 on 2025-12-29 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0011_vehicle_status_vehicle_typ_pojazdu_vehicle_uwagi'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_core.fleetcompany'),
        ),
    ]
