# Generated by Django 6.0 on 2025-12-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0013_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='data_waznosci_prawa_jazdy',
            field=models.DateField(blank=True, null=True),
        ),
    ]
