# Generated by Django 6.0 on 2025-12-30 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0014_alter_driver_data_waznosci_prawa_jazdy'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wydania', models.DateField(verbose_name='Data Wydania')),
                ('data_zwrotu', models.DateField(blank=True, null=True, verbose_name='Data Zwrotu')),
                ('uwagi', models.TextField(blank=True, null=True)),
                ('kierowca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='fleet_core.driver')),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='fleet_core.vehicle')),
            ],
        ),
    ]
