# Generated by Django 6.0 on 2026-01-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0015_vehiclehandover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceevent',
            name='typ_zdarzenia',
            field=models.CharField(choices=[('INSPEKCJA', 'Inspekcja'), ('NAPRAWA', 'Naprawa/Serwis'), ('PRZEGLAD', 'Przegląd okresowy'), ('BADANIE_TECH', 'Badanie Techniczne'), ('LEGALIZACJA', 'Legalizacja (Tachograf)')], default='NAPRAWA', max_length=50),
        ),
    ]
