# Generated by Django 6.0 on 2026-01-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0016_alter_serviceevent_typ_zdarzenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię Kierowcy')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko Kierowcy')),
                ('reservation_date', models.DateField(verbose_name='Data Rezerwacji')),
                ('vehicle_type', models.CharField(choices=[('OSOBOWE', 'Osobowe'), ('CIEZAROWE', 'Ciężarowe'), ('AUTOBUSY', 'Autobusy'), ('MOTOCYKLE', 'Motocykle'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('KOMBI', 'Kombi'), ('COUPE', 'Coupé')], max_length=30, verbose_name='Typ Pojazdu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_core.fleetcompany', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
    ]
