# Generated by Django 6.0 on 2026-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_core', '0017_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('OCZEKUJACE', 'Oczekujące'), ('PRZYJETE', 'Przyjęte'), ('ZATWIERDZONE', 'Zatwierdzone'), ('ODRZUCONE', 'Odrzucone')], default='OCZEKUJACE', max_length=20, verbose_name='Status Rezerwacji'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='company',
            field=models.CharField(max_length=200, verbose_name='Nazwa Firmy'),
        ),
    ]
